"""
services/user_service.py
-------------------------
Business logic for user accounts: registration and login.

SOLID – Single Responsibility:
  Only handles "what does it mean to register or log in?".
  It does NOT touch files (that's the repository's job) and does NOT build
  HTTP responses (that's the route's job).

SOLID – Dependency Inversion:
  Receives a UserRepository instance via __init__ (constructor injection).
  It calls the repository through its public interface, so it doesn't care
  whether the backing store is a file, SQLite, or PostgreSQL.
"""

import secrets
import bcrypt
from src.config import TOKEN_BYTE_LENGTH
from src.models.user import User
from src.repositories.user_repository import UserRepository


class UserService:
    """Handles registration, login, and logout for users."""

    def __init__(self, user_repo: UserRepository):
        """
        Parameters
        ----------
        user_repo : UserRepository
            Injected at app startup. The service never creates its own repo.
        """
        self._user_repo = user_repo

    # ------------------------------------------------------------------
    # Registration
    # ------------------------------------------------------------------

    def register(self, username: str, email: str, password: str) -> User:
        """
        Create a new user account.

        Raises ValueError if:
          - the email is already taken
          - the username is already taken

        Returns the newly created User object (without password exposed —
        callers should use user.to_public_dict() for API responses).
        """
        # Guard: unique email
        if self._user_repo.find_by_email(email):
            raise ValueError("A user with this email already exists.")

        # Guard: unique username
        if self._user_repo.find_by_username(username):
            raise ValueError("This username is already taken.")

        # Hash the password before storing.
        password_hash = bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()

        # Build the model – id and created_at are auto-generated by the model.
        user = User(username=username, email=email, password=password_hash)
        return self._user_repo.save(user)

    # ------------------------------------------------------------------
    # Login / Logout
    # ------------------------------------------------------------------

    def login(self, email: str, password: str) -> str:
        """
        Validate credentials and return a session token.

        Strategy:
          1. Find the user by email.
          2. Compare the password (plain text for now; will be hash compare later).
          3. Generate a cryptographically random token and persist it.
          4. Return the token to the caller (route) so it can send it to the client.

        Raises ValueError on invalid credentials (we deliberately give a vague
        message to prevent user enumeration attacks).
        """
        user = self._user_repo.find_by_email(email)
        if not user:
            raise ValueError("Invalid email or password.")

        # Backward-compatible password check:
        # New accounts store bcrypt hashes (start with "$2b$").
        # Old dev accounts stored plain text — fall back to plain comparison.
        if user.password.startswith("$2b$"):
            password_ok = bcrypt.checkpw(password.encode(), user.password.encode())
        else:
            password_ok = (user.password == password)

        if not password_ok:
            raise ValueError("Invalid email or password.")

        # secrets.token_hex produces a URL-safe hex string.
        token = secrets.token_hex(TOKEN_BYTE_LENGTH)
        user.tokens.append(token)
        self._user_repo.save(user)
        return token

    def logout(self, user: User, token: str) -> None:
        """
        Invalidate only the specific session token used for this request.
        Other sessions (e.g. extension while website is logged in) stay active.
        """
        if token in user.tokens:
            user.tokens.remove(token)
        self._user_repo.save(user)

    # ------------------------------------------------------------------
    # Profile helpers
    # ------------------------------------------------------------------

    def get_by_username(self, username: str) -> User:
        """
        Return a user by username, or raise ValueError if not found.
        Used by the public profile page.
        """
        user = self._user_repo.find_by_username(username)
        if not user:
            raise ValueError(f"User '{username}' not found.")
        return user

    def update_avatar(self, user_id: str, avatar_url: str) -> User:
        """Update the avatar URL for the given user."""
        user = self._user_repo.find_by_id(user_id)
        if not user:
            raise ValueError("User not found.")
        user.avatar_url = avatar_url
        return self._user_repo.save(user)
